# Generated by Ginger 5.3.4 on 2024-07-15 14:33

from ginger.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_schema_dbschema_alter_dbschema_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branch',
            new_name='dbschema_branch',
        ),
        migrations.AlterModelTable(
            name='dbschema_branch',
            table='dbschema_branch',
        ),
    ]
